<?php

namespace PaySimple\V4\Services;

use GuzzleHttp\Exception\GuzzleException;
use PaySimple\V4\Core\PaySimpleException;
use PaySimple\V4\Entities\RecurringPaymentSchedule;
use PaySimple\V4\Entities\Payment;

class RecurringPaymentsService extends Service
{
    /**
     * Collect payments on scheduled dates for the specified AccountId.
     *
     * @see https://documentation.paysimple.com/reference/recurringpayment
     * @param RecurringPaymentSchedule $scheduleInput
     * @return RecurringPaymentSchedule
     * @throws GuzzleException|\PaySimple\V4\Core\PaySimpleException
     */
    final public function new(RecurringPaymentSchedule $scheduleInput): RecurringPaymentSchedule
    {
        $requestData = $scheduleInput->toArray();
        $response = $this->client->post('recurringpayment', $requestData);

        if ($this->client->hasErrors() || ($response['error'] ?? false)) {
            throw PaySimpleException::fromApiResponse($response['data'] ?? [], $response['meta'] ?? (object)[]);
        }
        
        $apiResponseData = $response['data']; // This should be stdClass
        return RecurringPaymentSchedule::fromStdClass($apiResponseData);
    }

    /**
     * Returns a recurring payment object for the specified schedule id.
     *
     * @see https://documentation.paysimple.com/reference/get-recurring-payment
     * @param int $schedule_id
     * @return RecurringPaymentSchedule
     * @throws GuzzleException|\PaySimple\V4\Core\PaySimpleException
     */
    final public function get(int $schedule_id): RecurringPaymentSchedule
    {
        $response = $this->client->get(sprintf("recurringpayment/%s", $schedule_id));
        if ($this->client->hasErrors() || ($response['error'] ?? false)) {
            throw PaySimpleException::fromApiResponse($response['data'] ?? [], $response['meta'] ?? (object)[]);
        }
        $apiResponseData = $response['data']; // This should be stdClass
        return RecurringPaymentSchedule::fromStdClass($apiResponseData);
    }

    /**
     * Filterable and sortable list of all recurring payments.
     *
     * @see https://documentation.paysimple.com/reference/list-recurring-payments
     * @param array $filters
     * @return RecurringPaymentSchedule[]
     * @throws GuzzleException|\PaySimple\V4\Core\PaySimpleException
     */
    final public function list(array $filters = []): array
    {
        $response = $this->client->get('recurringpayment', $filters);
        if ($this->client->hasErrors() || ($response['error'] ?? false)) {
            throw PaySimpleException::fromApiResponse($response['data'] ?? [], $response['meta'] ?? (object)[]);
        }
        
        $apiResponseDataArray = $response['data']; // This is an array of stdClass objects
        $schedules = [];
        if (is_array($apiResponseDataArray)) {
            foreach ($apiResponseDataArray as $scheduleData) {
                if ($scheduleData instanceof \stdClass) {
                    $schedules[] = RecurringPaymentSchedule::fromStdClass($scheduleData);
                }
            }
        }
        return $schedules;
    }

    /**
     * Filterable and sortable list of recurring payments for a customer.
     *
     * @see https://documentation.paysimple.com/reference/list-customer-recurring-payments
     * @param int $customer_id
     * @return RecurringPaymentSchedule[]
     * @throws GuzzleException|\PaySimple\V4\Core\PaySimpleException
     */
    final public function customerList(int $customer_id): array
    {
        $response = $this->client->get(sprintf("customer/%s/recurringpayment", $customer_id));
        if ($this->client->hasErrors() || ($response['error'] ?? false)) {
            throw PaySimpleException::fromApiResponse($response['data'] ?? [], $response['meta'] ?? (object)[]);
        }
        
        $apiResponseDataArray = $response['data']; // This is an array of stdClass objects
        $schedules = [];
        if (is_array($apiResponseDataArray)) {
            foreach ($apiResponseDataArray as $scheduleData) {
                if ($scheduleData instanceof \stdClass) {
                    $schedules[] = RecurringPaymentSchedule::fromStdClass($scheduleData);
                }
            }
        }
        return $schedules;
    }

    /**
     * Retrieve payments generated by a given Recurring Payment.
     *
     * @see https://documentation.paysimple.com/reference/list-payments
     * @param int $schedule_id
     * @return Payment[]
     * @throws GuzzleException|\PaySimple\V4\Core\PaySimpleException
     */
    final public function paymentList(int $schedule_id): array
    {
        $response = $this->client->get(sprintf("recurringpayment/%s/payments", $schedule_id));
        if ($this->client->hasErrors() || ($response['error'] ?? false)) {
            throw PaySimpleException::fromApiResponse($response['data'] ?? [], $response['meta'] ?? (object)[]);
        }
        
        $apiResponseDataArray = $response['data']; // This is an array of stdClass objects
        $payments = [];
        if (is_array($apiResponseDataArray)) {
            foreach ($apiResponseDataArray as $paymentData) {
                if ($paymentData instanceof \stdClass) {
                    $payments[] = Payment::fromStdClass($paymentData);
                }
            }
        }
        return $payments;
    }

    /**
     * Modifies the specified recurring payment.
     *
     * @see https://documentation.paysimple.com/reference/update-recurring-payment
     * @param RecurringPaymentSchedule $scheduleInput
     * @return RecurringPaymentSchedule
     * @throws GuzzleException|\PaySimple\V4\Core\PaySimpleException
     */
    final public function update(RecurringPaymentSchedule $scheduleInput): RecurringPaymentSchedule
    {
        $requestData = $scheduleInput->toArray();
        $response = $this->client->put('recurringpayment', $requestData);

        if ($this->client->hasErrors() || ($response['error'] ?? false)) {
            throw PaySimpleException::fromApiResponse($response['data'] ?? [], $response['meta'] ?? (object)[]);
        }
        
        $apiResponseData = $response['data']; // This should be stdClass
        return RecurringPaymentSchedule::fromStdClass($apiResponseData);
    }

    /**
     * Stop a recurring payment from generating payments until resumed.
     *
     * @see https://documentation.paysimple.com/reference/suspend
     * @param int $schedule_id
     * @return RecurringPaymentSchedule
     * @throws GuzzleException|\PaySimple\V4\Core\PaySimpleException
     */
    final public function suspend(int $schedule_id): RecurringPaymentSchedule
    {
        $response = $this->client->put(sprintf('recurringpayment/%s/suspend', $schedule_id), []);
        if ($this->client->hasErrors() || ($response['error'] ?? false)) {
            throw PaySimpleException::fromApiResponse($response['data'] ?? [], $response['meta'] ?? (object)[]);
        }
        $apiResponseData = $response['data']; // This should be stdClass
        return RecurringPaymentSchedule::fromStdClass($apiResponseData);
    }

    /**
     * Stop a recurring payment from generating payments until a specified date.
     *
     * @see https://documentation.paysimple.com/reference/pause
     * @param int $schedule_id
     * @param \DateTime $end_date
     * @return RecurringPaymentSchedule
     * @throws GuzzleException|\PaySimple\V4\Core\PaySimpleException
     */
    final public function pause(int $schedule_id, \DateTime $end_date): RecurringPaymentSchedule
    {
        $final_end_date = $end_date->format('Y-m-d');
        $response = $this->client->put(sprintf('recurringpayment/%s/pause?enddate=%s', $schedule_id, $final_end_date), []);
        if ($this->client->hasErrors() || ($response['error'] ?? false)) {
            throw PaySimpleException::fromApiResponse($response['data'] ?? [], $response['meta'] ?? (object)[]);
        }
        $apiResponseData = $response['data']; // This should be stdClass
        return RecurringPaymentSchedule::fromStdClass($apiResponseData);
    }

    /**
     * Resume a paused or suspended schedule.
     *
     * @see https://documentation.paysimple.com/reference/resume
     * @param int $schedule_id
     * @return RecurringPaymentSchedule
     * @throws GuzzleException|\PaySimple\V4\Core\PaySimpleException
     */
    final public function resume(int $schedule_id): RecurringPaymentSchedule
    {
        $response = $this->client->put(sprintf('recurringpayment/%s/resume', $schedule_id), []);
        if ($this->client->hasErrors() || ($response['error'] ?? false)) {
            throw PaySimpleException::fromApiResponse($response['data'] ?? [], $response['meta'] ?? (object)[]);
        }
        $apiResponseData = $response['data']; // This should be stdClass
        return RecurringPaymentSchedule::fromStdClass($apiResponseData);
    }

    /**
     * Deletes recurring payment created in error.
     *
     * @see https://documentation.paysimple.com/reference/delete-recurring-payment
     * @param int $schedule_id
     * @return bool
     * @throws GuzzleException|\PaySimple\V4\Core\PaySimpleException
     */
    final public function delete(int $schedule_id): bool
    {
        $response = $this->client->delete(sprintf('recurringpayment/%s', $schedule_id));
        // Ensure consistent error handling, though it was likely already correct from previous refactors.
        if ($this->client->hasErrors() || ($response['error'] ?? false)) { 
            throw PaySimpleException::fromApiResponse($response['data'] ?? [], $response['meta'] ?? (object)[]);
        }
        return true;
    }


}
